services:
  db:
    image: mysql:9.0.1
    container_name: ${SERVICE}_db
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mpt-kpi-database:/var/lib/mysql

  frontend:
    container_name: ${SERVICE}_frontend
    platform: linux/amd64
    restart: always
    env_file: .env
    build:
      context: ./frontend/
    ports:
      - 127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}

  backend:
    container_name: ${SERVICE}_backend
    platform: linux/amd64
    restart: always
    env_file: .env
    build:
      context: ./backend/
    environment:
      - DATABASE_PORT
      - FRONTEND_PORT
      - BACKEND_PORT
      - DATABASE_USER
      - DATABASE_NAME
      - DATABASE_PASSWORD
    depends_on:
      - db

volumes:
  mpt-kpi-database:
     external: true
