version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mpt_kpi_db
      MYSQL_USER: kpi_user
      MYSQL_PASSWORD: kpi_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:5000"]
    depends_on:
      - db
    environment:
      - DEBUG=1

volumes:
  db_data:

